services:
  trigger-deployer:
    build: .
    image: trigger-deploy
    container_name: trigger-deployer
    ports:
      - "5001:5001"
    restart: always
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - /home/satrnd/trigger-deploy/trigger-logs:/app/trigger-logs
      - ./templates:/app/templates
      - ./static/:/app/static/
    networks:
      - trigger-deployer

networks:
  trigger-deployer:
    name: trigger-deployer-network
    driver: bridge
