services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dev-trigger-backend
    container_name: dev-trigger-backend
    ports:
      - "5002:5001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-trigger-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dev-trigger-frontend
    container_name: dev-trigger-frontend
    ports:
      - "3111:8082"
    env_file:
      - ./frontend/.env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-trigger-network
    restart: always

networks:
  dev-trigger-network:
    name: dev-trigger-network
    driver: bridge
