services:
  trigger-deployer:
    build: .
    image: trigger-deploy
    container_name: trigger-deployer
    ports:
      - "5000:5000"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - DEPLOY_TOKEN=${DEPLOY_TOKEN:-SATindonesia2026}
      - LOG_DIR=${LOG_DIR:-trigger-logs}
      - SERVERS_FILE=${SERVERS_FILE:-config/servers.json}
      - SERVICES_FILE=${SERVICES_FILE:-config/services.json}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-10}
    env_file:
      - .env
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ./trigger-logs:/app/trigger-logs
      - ./logs:/app/logs
      - ./config:/app/config
      - ./templates:/app/templates
      - ./static:/app/static
      - ./src:/app/src
      - ./scripts:/app/scripts
    networks:
      - dev-trigger-deploy

networks:
  dev-trigger-deploy:
    name: dev-trigger-deploy-network
    driver: bridge
