services:
  dev-trigger-deploy:
    build: .
    image: dev-trigger-deploy
    container_name: dev-trigger-deploy
    ports:
      - "3111:5000"
    restart: always
    environment:
      - TZ=Asia/Jakarta
      - DEPLOY_TOKEN=${DEPLOY_TOKEN:-SATindonesia2026}
      - LOG_DIR=${LOG_DIR:-trigger-logs}
      - SERVERS_FILE=${SERVERS_FILE:-config/servers.json}
      - SERVICES_FILE=${SERVICES_FILE:-config/services.json}
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-10}
      - DOCKER_ENABLED=${DOCKER_ENABLED:-true}
      - SHOW_DEMO_CREDENTIALS=${SHOW_DEMO_CREDENTIALS:-false}
    env_file:
      - .env
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - ./trigger-logs:/app/trigger-logs
      - ./logs:/app/logs
      - ./config:/app/config
      - ./templates:/app/templates
      - ./static:/app/static
      - ./src:/app/src
      - ./scripts:/app/scripts
      # Mount Docker socket for service monitoring
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dev-trigger-network

networks:
  dev-trigger-network:
    external: true
    name: dev-trigger-network